services:
  seerr:
    build:
      context: https://github.com/kernal32/Seerr.git#develop
      dockerfile: Dockerfile
      args:
        COMMIT_TAG: private
    image: seerr-home:local
    pull_policy: never
    container_name: seerr
    ports:
      - "5055:5055"
    volumes:
      - /media/config/overseerr:/app/config
    environment:
      TZ: Australia/Adelaide
    restart: unless-stopped
    networks:
      - npm-internal

networks:
  npm-internal:
    external: true
